# Generated by Django 4.1.4 on 2022-12-31 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vaccination_records", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personal_information",
            old_name="sex",
            new_name="gender",
        ),
    ]
