# Generated by Django 4.1.4 on 2022-12-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vaccination_records", "0002_rename_sex_personal_information_gender"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Email",
        ),
    ]
